repos:
  # Ruff linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter (includes type checking via ANN rules)
      - id: ruff
        name: ruff check (linting + type checking)
        args: [--fix, packages/]
        pass_filenames: false
      # Run the formatter
      - id: ruff-format
        name: ruff format (code formatting)
        args: [packages/]
        pass_filenames: false

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files

  # Run tests
  - repo: local
    hooks:
      - id: pytest
        name: pytest (run tests)
        entry: bash -c 'cd packages/noid-registry && uv run pytest tests/ -v && cd ../noid-transforms && uv run pytest tests/ -v && cd ../noid-spaces && uv run pytest tests/ -v'
        language: system
        pass_filenames: false
        always_run: true
        files: ^packages/
