# Transform examples in TOML format for testing LinkML schema

# Identity transform - just the string "identity"
transforms = [
  "identity",
  
  # Translation transform
  { translation = [10, 20, 5] },
  
  # Scale transform  
  { scale = [2.0, 1.5, 0.5] },
  
  # Map axis transform
  { mapAxis = [1, 0, 2] },
  
  # Homogeneous affine transform
  { homogeneous = [
    [2.0, 0, 0, 10],
    [0, 1.5, 0, 20], 
    [0, 0, 0.5, 5],
    [0, 0, 0, 1]
  ] },
  
  # Homogeneous projective transform
  { homogeneous = [
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0.001, 0.002, 0, 1]
  ] },
  
  # Displacement with simple string path
  { displacements = "path/to/displacement_field.zarr" },
  
  # Displacement with configuration object
  { displacements = { path = "path/to/field.zarr", interpolation = "linear" } },
  
  # Coordinate lookup table
  { lookup_table = { path = "path/to/coordinate_lut.zarr", interpolation = "linear", extrapolation = "nearest" } }
]